apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: microdemo
spec:
  replicas: 1
  selector:
    matchLabels: { app: worker }
  template:
    metadata:
      labels: { app: worker }
    spec:
      containers:
        - name: worker
          image: image-registry.openshift-image-registry.svc:5000/microdemo/worker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef: { name: app-config }
            - secretRef: { name: api-secret }
          resources:
            requests: { cpu: "25m", memory: "64Mi" }
            limits: { cpu: "200m", memory: "256Mi" }