apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api
  namespace: microdemo
spec:
  to: { kind: Service, name: api }
  port: { targetPort: http }
  tls: { termination: edge }
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  namespace: microdemo
spec:
  to: { kind: Service, name: frontend }
  port: { targetPort: http }
  tls: { termination: edge }