apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microdemo
  namespace: microdemo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          # frontend: keep path as-is
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  name: http
          # api: strip the /api prefix so Flask sees /messages
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  name: http
