apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microdemo
  namespace: microdemo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: microdemo.<INGRESS_IP>.nip.io   # e.g., microdemo.192.168.49.2.nip.io (minikube)
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  name: http
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  name: http