CREATE DATABASE IF NOT EXISTS messages_db;
USE messages_db;
CREATE TABLE IF NOT EXISTS messages (
id INT AUTO_INCREMENT PRIMARY KEY,
author VARCHAR(80) NOT NULL,
body TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'apppass';
GRANT ALL PRIVILEGES ON messages_db.* TO 'appuser'@'%';
FLUSH PRIVILEGES;